### ISSUE TITLE
Amplitude

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#10]

**Comment by beckysteele** [comment]
@petedejoy Do you have a link to an open pull request that I can review? Are there changes waiting in a branch somewhere?

**Comment by beckysteele** [comment]
In this [section](http://documentation.astronomer.io/v2/clickstream/destinations/amplitude.html#why-send-data-to-amplitude-using-astronomer-clickstream):
- One typo (library) in the second paragraph, this phrase: "You will only need to set up one event tracking libarary..."

And that's it for this one!

**Comment by paolaperaza** [comment]
@beckysteele done!
