### ISSUE TITLE
Clickstream: Add Troubleshooting line to DoubleClick doc

### ISSUE THREAD

**Issue by lindajguo** [astronomerio/documentation#101]
We should add a line somewhere in the DoubleClick Floodlight doc that says something along the lines of:

"When adding new Events to track with DoubleClick, make sure the Event `key` matches the Event name exactly"

For background, EBTH's DC issues were caused by the fact that the events were being called
`EBTH_Email Sign Up` in the configuration but the actual events were just `Email Sign Up`

**Comment by petedejoy** [comment]
Done.
