### ISSUE TITLE
2048 app doesn't seem to work on the first page load

### ISSUE THREAD

**Issue by abrongersma** [astronomerio/documentation#102]
@Dahs81 commented on [Fri Oct 27 2017](https://github.com/astronomerio/engineering/issues/516)

Chrome browser version 61.0.3163.100

**Comment by gregbrunk** [comment]
@abrongersma - I can probably hit this - not sure how it was originally built or why its happening, but I can dig in - I am assuming this is lower priority than Control Center at the moment though, so unless you tell me other-wise I will put this on the back-burner for now.

**Comment by abrongersma** [comment]
Back burner is fine. I was going to get with shad to see what he's experiencing. It's working fine for me.

**Comment by ryw** [comment]
We should also:

* Use Ajax to update data from Keen every 15 sec (rather than force refresh).
* Fix CSS to be more responsive, the page doesn't fit in my browser unless I make it full-width.

Let's knock this out over next few weeks; current state isn't a great reflection of our brand.

**Comment by ryw** [comment]
@abrongersma if you have any interest in working on this, please do - otherwise please unassign yourself.

**Comment by ryw** [comment]
seems to work on first load now, closing
