### ISSUE TITLE
Verify accuracy of library description

### ISSUE THREAD

**Issue by lmariel** [astronomerio/documentation#104]
The below paragraph is used in:
- clickstream/sources/nodejs
- clickstream/sources/python
- clickstream/sources/ruby

“You can use this library in your web server controller code. It is high-performing in that it uses an internal queue to make 'identify' and 'track' calls non-blocking and fast. It also batches messages and flushes asynchronously to our servers.”

**Comment by petedejoy** [comment]
Crossed-referenced with Segment docs, which confirm that this is correct.
