### ISSUE TITLE
Calq 

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#11]

**Comment by beckysteele** [comment]
In this [section](http://documentation.astronomer.io/v2/clickstream/destinations/calq.html#what-is-calq-and-how-does-it-work):
- The link "Learn more about Calq" goes to a 404 page

In this [section](http://documentation.astronomer.io/v2/clickstream/destinations/calq.html#astronomer-side):
- In the second sentence, "received" is spelled wrong.

That's it for this one!

**Comment by paolaperaza** [comment]
Fixed!
