### ISSUE TITLE
New/Updated/Planned Airflow Sources/Destinations

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#110]
- [ ] Using content from https://github.com/astronomerio/docker-airflow-saas/wiki/Standard-Hooks-and-Operators and build new page @ https://docs.astronomer.io/v2/apache_airflow/sources-and-destinations.html with what additional hooks/operators our distribution of Airflow includes
- [x] Link to page from https://trello.com/c/MttM0v78/3-more-airflow-hooks-operators-plugins
- [x] Link to page from https://trello.com/c/pVexblUz/17-new-updated-airflow-hooks-operators-plugins

**Comment by ryw** [comment]
@lindajguo i see this as fairly important for the success of the Airflow module - there's no clean spot where I can find all the pre-written code. It'd be nice if our page summarized all hooks/operators from standard Airflow, and then what hooks/operators we've written, with links to them.

What do you think?

**Comment by lindajguo** [comment]
@ryw I agree! Will build that in to the docs. We'll also have a public github repo that hosts all of the hooks/operators we've written to reference

**Comment by lindajguo** [comment]
@ryw I agree! Will build that in to the docs. We'll also have a public github repo that hosts all of the hooks/operators we've written to reference as well

**Comment by ryw** [comment]
let's get this up quickly

**Comment by lindajguo** [comment]
@ryw spoke to @bonominijl about this and he'd like to keep the page you linked to private for now. I think we can work with ttps://github.com/astronomerio/example-pipelines though. Chatting with Josh & his team on Monday to discuss re-organizing the repo + making sure we have safeguards in place to prevent sensitive customer info being pulished

**Comment by ryw** [comment]
@linda I didn't want to link to that private page, I wanted us to create a new page in docs (https://docs.astronomer.io/v2/apache_airflow/sources-and-destinations.html) that presents the information nicely and is kept up-to-date, and can then be linked to from the Trello cards I mentioned. Can you knock this out today?

**Comment by lindajguo** [comment]
@ryw started here https://docs.astronomer.io/v2/apache_airflow/sources-and-destinations.html

Obviously a lot more work to do on it but at least it's there if anyone's looking for a 1 stop shop of what's available

**Comment by ryw** [comment]
Awesome — good progress.

**Comment by ryw** [comment]
@linda - planning on doing anything else on this before closing out issue?

**Comment by petedejoy** [comment]
@ryw Just pushed up updates to this doc and the Astro Hooks doc. @benjamingregory threw this org together (https://github.com/airflow-plugins) and I linked to it at the top of each doc. Closing this for now,  but I'm going to come up with a better way to ensure that these stay up to date with the newest code and status of our hooks.
