### ISSUE TITLE
Add `Additional Functionality` and `Beyond the Basics` sections to destination docs

### ISSUE THREAD

**Issue by petedejoy** [astronomerio/documentation#119]
When we initially sprinted on docs, we intentionally left out these two sections for the sake of time. You can see what a doc with these sections will look like here:

(https://docs.astronomer.io/v2/clickstream/destinations/google-analytics.html)

I'm going to add these sections to destination docs, giving example calls and explaining the functionality of the features offered in the UI.

**Comment by petedejoy** [comment]
@ryw since this issue requires that I commit individually for each separate doc, would you rather I close this issue and open up separate ones for each doc I have yet to commit, or keep this one and commit all `Additional Feature` sections here?

**Comment by ryw** [comment]
I’d say create checklist in this issue, and crush it out

**Comment by petedejoy** [comment]
- [ ] Amplitude
- [ ] Mixpanel
- [ ] Keen
- [ ] KISSmetrics
- [ ] Facebook PIxel
- [ ] DoubleClick
- [ ] Intercom
- [ ] Lytics
- [ ] VWO
- [ ] Google Analytics
- [ ] Google Adwords

Note that, while this is not every destination, these are the ones with key `Additional Feature` capabilities in the UI. I will move on to the other less feature-rich destinations, once these are banged out.

**Comment by petedejoy** [comment]
Deployed.
