### ISSUE TITLE
instrument w Astronomer

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#129]
- [x] Setup new app in Astronomer
- [x] Add our snippet to https://github.com/astronomerio/documentation/blob/master/_includes/footer.html
- [x] Push data to at least Google Analytics

**Comment by petedejoy** [comment]
Docs site is sending `page` calls to GA and amplitude. I'll continue to get familiarized with the tools and figure out how to implement more specific calls that tell us more about users.
