### ISSUE TITLE
Customer.io

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#14]

**Comment by beckysteele** [comment]
In this [section](http://documentation.astronomer.io/v2/clickstream/destinations/customerio.html#why-send-data-to-customerio-using-astronomer-clickstream):
- There's an extra word in this phrase, "Customer.io also lacks a libraries..."

In this [section](http://documentation.astronomer.io/v2/clickstream/destinations/customerio.html#customerio-side):
- The "Customer.io" link goes to a 404 page

**Comment by paolaperaza** [comment]
@beckysteele fixed
