### ISSUE TITLE
Add Issue: Include section on managing plugins file

### ISSUE THREAD

**Issue by petedejoy** [astronomerio/documentation#146]
Added from Slack

**Comment by vparekh94** [comment]
@benjamingregory per our discussion, when you get the structure you want figured out, please add it here and I'll update the docs accordingly.

**Comment by benjamingregory** [comment]
@vparekh94 

Description of required/optional parameters should be included inline in each operator/hook file.

Readme at top level should be high level description of what the plugin contains and what purpose it serves.

See github.com/airflow-plugins for examples

{Example_Plugin_Name}_Plugin
  - Readme
  - __init__.py
  - operators
     - __init__.py
     - operator_one.py
     - operator_two.py
  - hooks
     - __init__.py
     - hook_one.py
     - hook_two.py_

**Comment by vparekh94** [comment]
Added under best practices section with https://github.com/astronomerio/documentation/commit/aee76bfd4ee3039d74e0eb26dc8bcee07fe5b08f

Thanks @benjamingregory !
