### ISSUE TITLE
Add Issue: Add high level info about airflow logging in db

### ISSUE THREAD

**Issue by petedejoy** [astronomerio/documentation#147]
Added from Slack

**Comment by vparekh94** [comment]
@tedmiston where in the docs do you think this belongs? I feel like we should include something about it since it's caused you a lot of headaches.

**Comment by tedmiston** [comment]
I'm not sure what this issue is for exactly - internal vs customer, which Airflow logs it's referring to, etc.

**Comment by vparekh94** [comment]
I was thinking externally - just something in the docs that tells you how logging works in the db.

However, when I think more about it, I'm not sure how customers will be able to directly access their metadata db, so I'll just close this for now and open another issue if we decide we want to add something.
