### ISSUE TITLE
Add issue: Add warning that setting schedule_interval as `@once` affects timestamp templating

### ISSUE THREAD

**Issue by petedejoy** [astronomerio/documentation#148]
Added from Slack

**Comment by ryw** [comment]
what's actionable step on this?

**Comment by vparekh94** [comment]
I creatre/created a bunch of issues like this as little Airflow "gotchas" (things that cost me time that aren't 100% obvious) to add to our docs. Not sure what section they belong in right now, but want them here for when we re-organize the airflow docs.

**Comment by ryw** [comment]
Just add them to our docs somewhere now, could be under new page "Airflow Tips" - so we can close out the issue + "ship"
