### ISSUE TITLE
DoubleClick Floodlight

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#15]

**Comment by beckysteele** [comment]
In the opening statement, we're missing a space in this phrase: `follow the steps below,your data`.

In [What is Doubleclick Floodlight and how does it work?](https://astronomerio.github.io/documentation/v2/clickstream/destinations/doubleclick-floodlight.html#what-is-doubleclick-floodlight-and-how-does-it-work), I recommend finding some useful resource written by Doubleclick support to link to, just in case the user wants to check out how it works directly from Google. Our description reads well, though, and the explanation of how we make things easier is great!

In the [Getting Started with Doubleclick Floodlight and Astronomer Clickstream](https://astronomerio.github.io/documentation/v2/clickstream/destinations/doubleclick-floodlight.html#getting-started-with-doubleclick-floodlight-and-astronomer-clickstream) section:
- I recommend providing some specific examples of tags that a user might get back from an agency. From experience, figuring out what `type` and `cat` are can be confusing. I'll send you two tags we received from a customer, which I recommend anonymizing and providing examples. This way, we can anticipate and (hopefully)  prevent requests for support.

**Comment by petedejoy** [comment]
Done.
