### ISSUE TITLE
Add information about how Airflow is better than SSIS packages

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/documentation#154]
We should have go to answers for when we're asked "How is this different from SSIS?"

**Comment by vparekh94** [comment]
Going to be putting chunks of information here before compiling into final wording:

Overall, there are problems that can be solved with both Airflow and SSIS, and if you're going to be working exclusively in a Microsoft environment SSIS may be the better choice. However, Airflow can be applied to a broader range of problems across different environments.

**Comment by petedejoy** [comment]
@vparekh94 what can I do to help with this?

**Comment by vparekh94** [comment]
Just throw any questions you see on Intercom on here (and then read over my final snippet before I commit it).

**Comment by vparekh94** [comment]
Should've named this issue better. but we need more info on what Airflow actually is on docs.

I added a few lines on the overview page, but going to open up additional issues before 3/7 over what we want to add to documentation vs resources.

Closing for now.
