### ISSUE TITLE
Go to Airflow story

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/documentation#155]
We should have a section of our docs that goes through a solving a full data problem with airflow (similar to a use case, but more of a story that showcases all of Airflow's capabilities).

This should show:
- Getting the data.
- Applying necessary transforms.
- Loading into a database.
- Making summary tables from a data model.
- Visualization of some sort.

**Comment by ryw** [comment]
could also be a blog post that we link to in the docs - good content for Airflow launch

**Comment by vparekh94** [comment]
Published blogpost today.
