### ISSUE TITLE
Facebook Pixel 

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#16]

**Comment by beckysteele** [comment]
I recommend mentioning a big recent change in the Facebook Pixel integration (from Segment). Several prospective customers considering the switch from them to us have questioned whether or not our destination connector accommodated for this change:
- Facebook has deprecated their modular “Ads For Websites” suite, which previously comprised Facebook Custom Audiences and Facebook Conversion Tracking. We’ve consolidated those two destinations into the new and improved Facebook Pixel destination!

In this [section](http://documentation.astronomer.io/v2/clickstream/destinations/facebook-pixel.html#facebook-pixel-side):
- The `facebook-pixel1` image is not showing
- I think the end of paragraph 2 accidentally came to an abrupt ending: "...which will be a 15 digit number that uniquely identifies both your site." Both your site and... not sure what else goes here.

**Comment by paolaperaza** [comment]
@beckysteele all fixed. Thanks so much for that feedback 😄
