### ISSUE TITLE
Add Doc with Airflow sign-up instructions

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#162]
@rbradk needed to send something out today to Andrew Maguire from PMC who wants to play around with Airflow before a demo. We whipped out [this google doc](https://docs.google.com/document/d/1YI5hfjyXD0BObu1cUjPRRbCtq2ykQJmD8365lTRrNwI/edit?ts=5a4fe13b#) with a super brief step-by-step and accompanying screenshots, but we should copy this over onto our actual docs site. 

_Note: Right now we're thinking to NOT make the `olympus mons` upgrade code public, the doc will just have copy that asks readers to reach out to us for it. Those who have reached out will have received the code from us already_

**Comment by ryw** [comment]
agree, do not make code public

**Comment by rbradk** [comment]
+1

--

[image: Astronomer Logo] <https://www.astronomer.io/>

R. Brad Kirn
Director, Data Solutions

Mobile: +1.859.630.6656 <(859)%20859-6306656> • Online: astronomer.io
<https://www.astronomer.io/>

Download our new ebook. <http://marketing.astronomer.io/guide/> From Volume
to Value—A Guide to Data Engineering.

**Comment by paolaperaza** [comment]
All done and live @rbradk ! Closing this issue out. 

Let me know if you get any feedback on this doc from the PMC folks or anyone else you end up sending to.

**Comment by rbradk** [comment]
Nice! will do.

--

[image: Astronomer Logo] <https://www.astronomer.io/>

R. Brad Kirn
Director, Data Solutions

Mobile: +1.859.630.6656 <(859)%20859-6306656> • Online: astronomer.io
<https://www.astronomer.io/>

Download our new ebook. <http://marketing.astronomer.io/guide/> From Volume
to Value—A Guide to Data Engineering.

**Comment by benjamingregory** [comment]
@paolaperaza Not a huge deal but those images on the page look really low res to me.

**Comment by benjamingregory** [comment]
This is what I'm seeing. On my screen it's all a bit blurry.

<img width="693" alt="screen shot 2018-01-09 at 12 01 26 pm" src="https://user-images.githubusercontent.com/8160412/34735402-f2b18996-f534-11e7-9703-bf22030582a6.png">
<img width="779" alt="screen shot 2018-01-09 at 12 01 19 pm" src="https://user-images.githubusercontent.com/8160412/34735403-f2c842bc-f534-11e7-90c5-d268cf7f5d01.png">

**Comment by ryw** [comment]
should have used PNG

**Comment by rbradk** [comment]
Paola - I exported each screenshot as a PNG and attached them here. The
numbers *may* be off btw.

--

[image: Astronomer Logo] <https://www.astronomer.io/>

R. Brad Kirn
Director, Data Solutions

Mobile: +1.859.630.6656 <(859)%20859-6306656> • Online: astronomer.io
<https://www.astronomer.io/>

Download our new ebook. <http://marketing.astronomer.io/guide/> From Volume
to Value—A Guide to Data Engineering.

**Comment by paolaperaza** [comment]
@rbradk @benjamingregory @ryw - will get these images updated today and close out when that's done.

**Comment by paolaperaza** [comment]
@benjamingregory updated all the images - they were originally PNG's since I had to upload them to GitHub first, but I took a new set. Let me know if these look better?

@rbradk I couldn't find the ones you attached, but hopefully these ones I just put up work.

**Comment by benjamingregory** [comment]
LGTM

**Comment by ryw** [comment]
me too - closing
