### ISSUE TITLE
Port over "Best Practices for Passing up Data Formats" to Support Portal

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#166]
Add based on Taylor's explanation in [this issue](https://github.com/astronomerio/astronomer-saas/issues/138), based on what we sent to Roadtrippers

**Comment by vparekh94** [comment]
@tedmiston ported over your response from https://github.com/astronomerio/astronomer-saas/issues/138 into an Intercom resource.

Question for you - does our Clickstream loader specify column order on COPY commands? The method you described would change a table's column order and potentially cause a misaligned COPY statement. 

The method I described below just makes a new table, but if the clickstream loader specifies order, I'll modify it accordingly.

```
Our Clickstream module uses Apache Spark's schema inferencing with 100% sampling on the first batch of data received for a given event type.

This means that if you were to create a new custom event, we would look at all values of that event for the first batch of data received and chose the column type accordingly.

Note that there's a hierarchy of data types here, so if the first batch of a new event contained 100 values, 99 INTs and 1 VARCHAR, the data type would be inferred to be a VARCHAR (since all INTs are VARCHARs but not all VARCHARs are INTs). 

Once a column's data type is set, we don't attempt to change it later. 

If you decide that you need to change a column's data type, we recommend creating a new table with the right data type for the column, inserting the old table into the new table (with the new datatype for the column explicitly cast), and then drop the old table and rename the new one. 

This preserves column order and prevents the COPY statement from being misaligned when your data goes from S3 to Redshift. 
```

**Comment by tedmiston** [comment]
+1 to what you said / what we talked about this morning.

I'm not positive about order preservation since it's abstracted away from us in the Databricks copy code, not something we wrote.

**Comment by vparekh94** [comment]
Sounds good - I'll add the bit about pausing the DAG to intercom. Closing this for now.
