### ISSUE TITLE
Update Sources/Destinations repo with new list

### ISSUE THREAD

**Issue by benjamingregory** [astronomerio/documentation#169]
We've added a few new hooks/operators since this was first written:
https://docs.astronomer.io/v2/apache_airflow/sources-and-destinations.html

Here is the running list:
https://github.com/airflow-plugins/table-of-contents

**Comment by petedejoy** [comment]
@benjamingregory Viraj and I discussed pulling out all the code snippets from the "hooks" and "operators" docs and just including a link to the github file instead- this will ensure that they're up to date and we won't need to actively maintain them in the docs going forward. What are your thoughts on that?

**Comment by benjamingregory** [comment]
I agree with that. I think this task can be completed by just adding links to the specific hook/operator in Github.

**Comment by petedejoy** [comment]
Cool I'll get that done with this issue.

**Comment by ryw** [comment]
I think theres benefit to maintaining https://docs.astronomer.io/v2/apache_airflow/sources-and-destinations.html for SEO purposes - if we update it (and our docs) more often, it'll get more Google juice.

**Comment by benjamingregory** [comment]
@ryw Agreed - Given Pete's update, I'm closing this issue for now.
