### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#17]

**Comment by beckysteele** [comment]
@petedejoy Do you have a link to an open pull request that I can review? Are there changes waiting in a branch somewhere?

**Comment by beckysteele** [comment]
Ah, my favorite.

In the [Getting Started with Google Analytics...](https://astronomerio.github.io/documentation/v2/clickstream/destinations/google-analytics.html#getting-started-with-google-analytics-x-astronomer) section:
- I'd recommend extracting "Also, you will need to remove Google Analytics’ snippet from your page if you were using it outside of Astronomer" and making it a bold note that the user sees first thing. This was a frequent cause for support, and would make a nice "before you do anything, do this" step.
- (ignore if this is coming) I recommend one of those fancy video screen shots for the UI configuration. So many (good) options to tinker with in this one, and a picture will go a long way.
- In the third paragraph (if you don't count the first sentence), there's a typo in this statement: "and you will be brough to"
- In the "What happens now?" area, can we quantify how long this should take (with the help of engineering)? "Google Analytics will start automatically collecting data on your site or mobile app. It takes Google a couple of hours to process this data and add it to your reports, but you should still see events showing up in the real-time events dashboard." <-- In the past, it has taken between 12-24 hours for events to populate a user's GA dashboard, and once there, the events are basically real-time. This initial lag can create support requests.
- Same comment as ^^ for iOS and Android.

In the [Page & Screen](https://astronomerio.github.io/documentation/v2/clickstream/destinations/google-analytics.html#page--screen) section:
- Change this statement in the fourth paragraph to read Astronomer, not Segment, and change "Ive" to "If": "Ive you’ve set an application name in your Android or iOS project, Segment will grab the name..."

In the [Identify](https://astronomerio.github.io/documentation/v2/clickstream/destinations/google-analytics.html#identify) section:
- Link to Google's Terms of Service directly

I know this is one of the largest destinations to build out. I'm sharing a document in our chat that might help when continuing to build it out.  Nice job!
