### ISSUE TITLE
Fix link to Airflow Podcast 

### ISSUE THREAD

**Issue by benjamingregory** [astronomerio/documentation#170]
Link to Soundcloud is not connected
https://www.astronomer.io/blog/announcing-the-airflow-podcast/

Also should link to iTunes, Overcast, and Stitcher.

**Comment by petedejoy** [comment]
Fixed link, can't link to iTunes because they don't have webpages for podcasts, sent an application to Stitcher this morning, still waiting to hear back. Will update if they take us.

**Comment by benjamingregory** [comment]
@petedejoy What's wrong with using https://itunes.apple.com/us/podcast/the-airflow-podcast/id1337349579?mt=2?

**Comment by petedejoy** [comment]
Oh damn for some reason couldn't find that when browsing Apple's site. Will update now!
