### ISSUE TITLE
remove lame + broken pages from nav

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#173]
These pages are not interesting enough to take up nav space:

* https://docs.astronomer.io/v2/apache_airflow/hooks/*
* https://docs.astronomer.io/v2/apache_airflow/operators/*

found some that are broken too (salesforce)

we should just remove them all from left nav, maybe even delete them from docs if we're not going to build them out

**Comment by petedejoy** [comment]
@ryw Just to clarify, you want to remove all specific hook/operator docs from the side nav and just try to push people towards github.com/airflow-plugins in the overview docs?

**Comment by ryw** [comment]
yes

**Comment by petedejoy** [comment]
Done
