### ISSUE TITLE
merge content

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#174]
Pull any interesting content from <https://github.com/astronomerio/team/wiki/CLI> into <https://docs.astronomer.io/v2/apache_airflow/cli.html> then delete <https://github.com/astronomerio/team/wiki/CLI> (our internal wiki is not the right place for this content).

**Comment by vparekh94** [comment]
@ryw are we going to open the CLI repo up again? The one referenced in that doc to hack on the CLI is read only. Other than that, everything else is up to date

**Comment by schnie** [comment]
@vparekh94 those docs refer to the og python cli. All CLI's are open source. New one is here: https://github.com/astronomerio/astro-cli

**Comment by vparekh94** [comment]
Closed with most recent commit. Let's keep enterprise CLI docs separate from this for now too.
