### ISSUE TITLE
Add details on S3 bucket policy necessary for Airflow operators

### ISSUE THREAD

**Issue by benjamingregory** [astronomerio/documentation#176]
When using the "....to-s3" and "...from-s3" operators, it is best to set a policy restricted to a dedicated s3 bucket to use in your Airflow s3 connection object. This policy will need to read, write, and delete objects. 

An example policy allowing this is below:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "1",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::{bucketName}",
                "arn:aws:s3:::{bucketName}/*"
            ]
        }
    ]
}
```

For more details, please visit: https://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html#using-with-s3-actions-related-to-bucket-subresources

**Comment by petedejoy** [comment]
Reassigning to @vparekh94, as he's taking point on restructuring Airflow docs.

**Comment by vparekh94** [comment]
I added it to the part in best practices where we talk about using an intermediary. When we restructure the docs to be more tutorial like we'll move it a bit. 

Closing this for now.
