### ISSUE TITLE
Write Support Article: Astronomer vs. Keen

### ISSUE THREAD

**Issue by petedejoy** [astronomerio/documentation#182]
@benjamingregory- @rbradk forwarded along your response to the question below. I'm happy to whip this up into a support article, but could you drop in anything else you know about Keen's product? I'm not familiar with it at all.

Astronomer provides an source/destination agnostic platform and focuses on the processing and routing your data but leaves the storage and retrieval to other vendors. Keen (for the most part) uses their own managed database (a hosted Cassandra service) to store your data and provides a REST API to retrieve this data in your app and create custom visualization in your dashboard.

**Comment by benjamingregory** [comment]
| Category | Astronomer | Keen IO |
|----------|-------------|---------|
|Compatibility with Analytics.js| Yes | No |
| Clickstream to 3rd party integrations | Yes | No |
|Clickstream to Redshift | Yes | No |
|Clickstream to S3 | Yes | Yes |
|Clickstream to BigQuery | Coming soon... | Beta (Not Actively Supported) |
| Hosted Airflow | Yes | No |
|Deployment Options | Open-Source, Hosted Cloud, Private Cloud | Hosted Cloud |
|Cloud Service Provider | AWS (soon to be GCS) | AWS |
| Data Storage | Bring Your Own Database | Required hosted data storage with access via API |
| Visualization Library | No | Yes |
| Query Engine | No - Data is not stored by Astronomer | Yes - NoSQL with custom syntax |
| Pricing | Based on events processed (for clickstream) and concurrent tasks (for Airflow) | Based on events processed, properties scanned, and access key creation |

**Comment by benjamingregory** [comment]
Closed with https://support.astronomer.io/general/astronomer-vs-keen
