### ISSUE TITLE
Write article on GDPR for support site

### ISSUE THREAD

**Issue by petedejoy** [astronomerio/documentation#186]
Per @rbradk's request, consolidating a bunch of GDPR information we have into a specific FAQ.

**Comment by timbrunk** [comment]
@petedejoy - adding this to 4/18 milestone as we need it asap. 

Check out this for sample post: https://segment.com/blog/segment-and-the-gdpr/

**Comment by petedejoy** [comment]
@timbrunk I have this up already, going to close out this issue and continue the conversation/updates in /team issue number 85.

https://support.astronomer.io/general/astronomer-and-gdpr-compliance
