### ISSUE TITLE
Guide on accessing/authenticating GCP products from within Airflow on Astronomer

### ISSUE THREAD

**Issue by benjamingregory** [astronomerio/documentation#187]

**Comment by schnie** [comment]
@benjamingregory should we link to https://enterprise.astronomer.io/ guides?

**Comment by benjamingregory** [comment]
@schnie This issue refers to accessing GCP products (BigQuery, GCS, etc.) from airflow; not running the platform on GCP.

Re-titled the issue to clarify this.

**Comment by vparekh94** [comment]
@benjamingregory I have a rough draft here:                       

https://github.com/vparekh94/gcp_example/blob/master/Google%20Big%20Query%20in%20Astronomer%20Cloud.ipynb

1) Which repo airflow-plugins do you think this belongs in?

**Comment by benjamingregory** [comment]
@vparekh94 This is great. Let's put it in the `Getting-Started` repo.

**Comment by benjamingregory** [comment]
@vparekh94 Actually, given that these docs relate to accessing GCS, specifically from within the Astronomer platform, maybe more appropriate to keep them in the Astronomer docs? What do you think?

**Comment by vparekh94** [comment]
I think it can go on both because the `CustomBigQuery` operator that Andrew wrote works agnostically of the Astronomer Platform (he added some metadata output to the logs), and the EE part would work for any Airflow 1.9 install.

Think we can put it Getting Started to begin with and port it over to Astronomer Docs later?

Does that work for you?

**Comment by benjamingregory** [comment]
@vparekh94 Let's keep it in one place or the different versions are going to fall out of sync. Getting Started works for me; I see your logic. 

We'll need to do some quick reconfiguring of the `Getting Started` file structure because  right now it's specifically geared towards Getting Started with _creating_ Plugins but I like the idea of expanding that to cover more ground. Throw it in there and I'll add some language to the readme to explain it.

**Comment by vparekh94** [comment]
Closed with this:

https://github.com/airflow-plugins/Getting-Started/commit/1e8a6ea037da5c000c255b0698790652c44f8954
