### ISSUE TITLE
KISSMetrics

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#22]

**Comment by beckysteele** [comment]
In this [section](http://documentation.astronomer.io/v2/clickstream/destinations/kissmetrics.html#what-is-kissmetrics-and-how-does-it-work):
- the "Learn more about Kissmetrics" link is broken
- Also, I recommend showing it as KISSmetrics throughout the docs

That it!

**Comment by paolaperaza** [comment]
All of the above fixed
