### ISSUE TITLE
Mixpanel

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#24]

**Comment by beckysteele** [comment]
@petedejoy Do you have a link to an open pull request that I can review? Are there changes waiting in a branch somewhere?

**Comment by beckysteele** [comment]
(this one gave me a chuckle)
In this [section](http://documentation.astronomer.io/v2/clickstream/destinations/mixpanel.html#astronomer-side):
- "Nogit puw" should probably be "Now,". I blame Dagny.

**Comment by paolaperaza** [comment]
hahah, that git push gettin in the way. All fixed!
