### ISSUE TITLE
Resonate

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#27]
Some content in there, needs review

**Comment by petedejoy** [comment]
@beckysteele can you look over the code in this doc? Not sure, but doesn't look right to me.

**Comment by beckysteele** [comment]
You were correct about that code, @petedejoy.

In particular, the User Tracking ID section code snippet is incorrect. It should look something like this, but it's straight up missing the user_tracking_key. My best guess is that the resnc3 parameter is the user tracking key. 

`<IMG SRC="https://ds.reson8.com/insights.gif?rand=[cache_buster]&t=0&pixt=resonate&advkey=my_advkey&opptykey=my_opptykey&evkey=my_event_key&evtype=custom&resnc1=esp&resnc2=open&resnc3=%%SomeUserID%%&" WIDTH=1 HEIGHT=1 BORDER=0>`

To be honest, I'm not entirely sure where this came in, as it was a request that we add the User Tracking pixel by Resonate on behalf of EBTH. We could reach out directly to Resonate, but we'd want to see if EBTH is using them first.

Other than that, this connector looks good.

**Comment by paolaperaza** [comment]
@petedejoy leavin this to you to check out

**Comment by petedejoy** [comment]
Example code has been updated.
