### ISSUE TITLE
Rubicon

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#29]

**Comment by paolaperaza** [comment]
Just pushed up a v.1, for some reason it didn't link the commit on here, but check out [this link](https://github.com/astronomerio/documentation/commit/13945c1335943ef863807b062a6cb2539a3ed111) to see the latest changes.

**Comment by beckysteele** [comment]
In this [section](http://documentation.astronomer.io/v2/clickstream/destinations/rubicon.html#astronomer-side):
- It looks like there's an unlinked image called "rubicon1" that's meant to be showing.

Other than that, looks great!

**Comment by paolaperaza** [comment]
rubicon1 image fixed
