### ISSUE TITLE
Wiki: Connections

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#35]
@ryw commented on [Wed Sep 27 2017](https://github.com/astronomerio/customer/issues/194)

@lindajguo commented on [Wed Sep 20 2017](https://github.com/astronomerio/pro-beta/issues/1)

combine common connections

**Comment by sammf** [comment]
All currently supported Clickstream sources and destinations (as they appear in the front-end) will be re-written as a part of the new docs push. Appropriate tasks have been created in the documentation repository on GitHub.
