### ISSUE TITLE
Wiki: Hooks & Operators

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#36]
@ryw commented on [Wed Sep 27 2017](https://github.com/astronomerio/customer/issues/193)

@lindajguo commented on [Wed Sep 20 2017](https://github.com/astronomerio/pro-beta/issues/2)

Finish documenting hooks & operators

**Comment by sammf** [comment]
This will be covered and maintained as a part of the new docs push. Appropriate tasks have been created in the documentation repository on GitHub.
