### ISSUE TITLE
Wiki: DAG Deployment

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#37]
@ryw commented on [Wed Sep 27 2017](https://github.com/astronomerio/customer/issues/192)

@lindajguo commented on [Wed Sep 20 2017](https://github.com/astronomerio/pro-beta/issues/4)

Fix sample DAG

**Comment by sammf** [comment]
This will be covered and maintained as a part of the new docs push. Appropriate tasks have been created in the documentation repository on GitHub.
