### ISSUE TITLE
Identify what existing sections of the docs site need to be removed

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#38]
@ryw commented on [Wed Sep 27 2017](https://github.com/astronomerio/customer/issues/191)

@benjamingregory commented on [Mon Sep 11 2017](https://github.com/astronomerio/team/issues/2)

The metalsmith site will be deprecated in the coming weeks in favor of incorporating the docs into the main website. In preparation for that, [the existing docs site](https://docs.astronomer.io/docs/1.0/) needs to be reviewed and legacy documents (no longer relevant to Astronomer's immediate vision) identified. Documents that do not have immediate relevancy but could be relevant later can be moved to a hidden "graveyard" folder to be brought back at a later date.

Examples include:

- Are standard pipelines still relevant?
- Are we still working on Aries? Should [existing diagrams](https://docs.astronomer.io/docs/1.0/guides/concepts/batch/) and guides be removed?
- Should [batch sources + destinations](https://docs.astronomer.io/docs/1.0/connectors/sources/) be removed?
- Can [v1 of front end](https://docs.astronomer.io/docs/1.0/gui/gui-v1/) be officially removed from GUI section?
- What APIs will be under immediate release (currently have [4 listed - Houston, Hubble, Sputnik, GoldenEye](https://docs.astronomer.io/docs/1.0/api/))?
- What detail should clickstream libraries go into? Can they link back to Segment given they are technically the official documentation for analytics.js or should we conversely try to mirror their docs more comprehensively?

---

@thisisamurray commented on [Tue Sep 12 2017](https://github.com/astronomerio/team/issues/2#issuecomment-328845593)

I can update the API section of the Docs, but just to let you know that it is no longer the source of truth for API plans and can be scrapped. Can replace it in favor of https://astronomerio.github.io/public-api-houston. It will get continual updates on the Public API.

---

@benjamingregory commented on [Tue Sep 12 2017](https://github.com/astronomerio/team/issues/2#issuecomment-328858070)

Thanks @thisisamurray -- I'll make a note of that. 

I will also publish a list of what documentation from the existing site / outside repos will be removed prior to closing this issue. New documentation (from Phabricator) will be listed in a separate issue after @paolaperaza and I have a chance to review: https://github.com/astronomerio/team/issues/1

---

@benjamingregory commented on [Tue Sep 12 2017](https://github.com/astronomerio/team/issues/2#issuecomment-328934089)

@ryw @sammf Can you advise on some of the above questions?

Essentially, as Astronomer Pro Beta becomes a larger focus, what under the essentially range of docs should be taken offline for the time being?

---

@ryw commented on [Wed Sep 13 2017](https://github.com/astronomerio/team/issues/2#issuecomment-329323693)

let's review together in person

---

@sammf commented on [Thu Sep 14 2017](https://github.com/astronomerio/team/issues/2#issuecomment-329502525)

My preference would be to do the following:

1.  Immediately deprecate any section of current docs site that references anything other than the core Clickstream product (remove references to batch, Pro, and Aries).
2. Temporarily host Pro Beta documentation in Github while the new docs site is being built out. This should be fine, as most of the initial Pro Beta customers will be technical users.
3. Build out new docs site w/ walkthroughs, tutorials, core concepts, and technical documentation.
4. Deprecate the old docs site and temporary Github documentation.

The temporary Github docs should just have the basics...
 -  Core Airflow Concepts (Scheduler, Dags, Dag Runs, Tasks, Task Runs, Etc...)
 -  Simple Sample DAG  (can be used as a starting template for DAG syntax)
 -  CLI (including Astronomer and Airflow Commands)
 -  Airflow Operators (Overview for each available operator -- required/optional parameters)
 -  Airflow Connections (setup in GUI, required fields for each connections type)
 -  Sample DAG Deployment Tutorial (in order to support all environments,  sample DAG shouldn't require any connections)

---

@ryw commented on [Thu Sep 14 2017](https://github.com/astronomerio/team/issues/2#issuecomment-329513280)

@sammf when you say "new docs site" are you referring to the idea of building docs into the new static website?

---

@sammf commented on [Thu Sep 14 2017](https://github.com/astronomerio/team/issues/2#issuecomment-329525522)

Yes - the longterm replacement for the metalsmith site.

I believe the FE team is having a docs site kickoff on Monday morning.

---

@sammf commented on [Thu Sep 14 2017](https://github.com/astronomerio/team/issues/2#issuecomment-329606935)

@ryw - Are you okay w/ this approach? If so, any prefernce how we handle the temporary handling of documentation in Github (wiki vs readme)?

Once we nail those details down, @lindajguo can start deprecating pages in metalsmith and creating the content outlined above in GitHub.

---

@ryw commented on [Fri Sep 15 2017](https://github.com/astronomerio/team/issues/2#issuecomment-329779829)

I'm down with this plan, as long as it's **very temporary**.

---

@sammf commented on [Fri Sep 15 2017](https://github.com/astronomerio/team/issues/2#issuecomment-329786402)

@ryw - Agreed.

@benjamingregory - Please show @lindajguo how to start deprecating/reorganizing pages on the current doc site, as I'd like her to run point on that process.

@lindajguo - Can you also start building out the temporary Pro Beta docs site in GitHub? I'm happy to help with this as well. @ryw - Do you have any preferences on how this is stored in GitHub (wiki vs readme)?

---

@ryw commented on [Fri Sep 15 2017](https://github.com/astronomerio/team/issues/2#issuecomment-329787337)

wiki in a public repo is fine w/ me

---

@benjamingregory commented on [Fri Sep 15 2017](https://github.com/astronomerio/team/issues/2#issuecomment-329913359)

Handoff to @lindajguo happened earlier today.

---

@lindajguo commented on [Fri Sep 15 2017](https://github.com/astronomerio/team/issues/2#issuecomment-329921464)

FYI - https://github.com/astronomerio/pro-beta/wiki

---

@ryw commented on [Fri Sep 15 2017](https://github.com/astronomerio/team/issues/2#issuecomment-329936731)

Good start - keep 'em coming :)

---

@sammf commented on [Mon Sep 18 2017](https://github.com/astronomerio/team/issues/2#issuecomment-330274356)

@lindajguo - Setting up some time today for us to quickly run through the current docs site in hopes of closing out this task soon.

**Comment by sammf** [comment]
This has been tasked out to individual tasks in the documentation repo. -- Closing.
