### ISSUE TITLE
Analytics.js

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#4]
[Current table of contents:](https://astronomerio.github.io/documentation/v2/clickstream/sources/analyticsjs.html)

- Getting Started with Astronomer Clickstream - Website
  - Create a Client-Side Source in the Astronomer UI
  - Copy & Paste the Snippet
  - Identify Your Users
  - Track Your Users’ Actions

**Comment by beckysteele** [comment]
Nothing to add--looks great!
