### ISSUE TITLE
Add Google Analytics Data Mapping

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#40]
@ryw commented on [Wed Sep 27 2017](https://github.com/astronomerio/customer/issues/188)

@benjamingregory commented on [Mon Jun 19 2017](https://github.com/astronomerio/astronomer-docs/issues/62)

---

@beckysteele commented on [Wed Jun 21 2017](https://github.com/astronomerio/astronomer-docs/issues/62#issuecomment-310161225)

@benjamingregory was this specific to the GA recipe?

---

@benjamingregory commented on [Thu Jul 27 2017](https://github.com/astronomerio/astronomer-docs/issues/62#issuecomment-318379020)

@beckysteele Yes - for this page https://github.com/astronomerio/astronomer-docs/blob/master/1.0/batch/standard-pipelines/google-analytics/to-redshift.md

---

@benjamingregory commented on [Wed Sep 13 2017](https://github.com/astronomerio/astronomer-docs/issues/62#issuecomment-329201775)

Removing myself as docs transition to new website with updated priority.

**Comment by sammf** [comment]
All currently supported Clickstream sources and destinations (as they appear in the front-end) will be re-written as a part of the new docs push. Appropriate tasks have been created in the documentation repository on GitHub.
