### ISSUE TITLE
Build connector page for outbrain

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#43]
@ryw commented on [Wed Sep 27 2017](https://github.com/astronomerio/customer/issues/185)

@benjamingregory commented on [Sun Jul 23 2017](https://github.com/astronomerio/astronomer-docs/issues/105)

---

@ryw commented on [Tue Sep 26 2017](https://github.com/astronomerio/astronomer-docs/issues/105#issuecomment-332377355)

assuming this is aries-related, closing

---

@benjamingregory commented on [Tue Sep 26 2017](https://github.com/astronomerio/astronomer-docs/issues/105#issuecomment-332385406)

This is related to Analytics.js - https://github.com/astronomer-integrations/analytics.js-integration-outbrain

@beckysteele Do you know if still relevant/used?

---

@beckysteele commented on [Wed Sep 27 2017](https://github.com/astronomerio/astronomer-docs/issues/105#issuecomment-332565718)

No customers are currently using Outbrain.  I do recommend a connector page being built if we intend to offer Outbrain as part of our Analytics.js offering. Deferring to your judgment @ryw @benjamingregory @lindajguo!

**Comment by sammf** [comment]
All currently supported Clickstream sources and destinations (as they appear in the front-end) will be re-written as a part of the new docs push. Appropriate tasks have been created in the documentation repository on GitHub.
