### ISSUE TITLE
Build Connector Page for Kenshoo Infinity Pixel

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#45]
@ryw commented on [Wed Sep 27 2017](https://github.com/astronomerio/customer/issues/183)

@benjamingregory commented on [Wed May 24 2017](https://github.com/astronomerio/astronomer-docs/issues/4)

**Comment by sammf** [comment]
All currently supported Clickstream sources and destinations (as they appear in the front-end) will be re-written as a part of the new docs push. Appropriate tasks have been created in the documentation repository on GitHub.
