### ISSUE TITLE
Build Connector Page for Facebook App Events

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#49]
@ryw commented on [Wed Sep 27 2017](https://github.com/astronomerio/customer/issues/179)

@benjamingregory commented on [Thu Jul 20 2017](https://github.com/astronomerio/astronomer-docs/issues/100)

https://github.com/astronomer-integrations/integration-facebook-app-events

**Comment by sammf** [comment]
All currently supported Clickstream sources and destinations (as they appear in the front-end) will be re-written as a part of the new docs push. Appropriate tasks have been created in the documentation repository on GitHub.
