### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#5]
[Current Table of Contents:](https://astronomerio.github.io/documentation/v2/clickstream/sources/android.html)

- Getting Started with Astronomer Clickstream - Android
  - Create an Android Source in the Astronomer UI
  - Install the SDK
  - Initialize the Client
  - Add Permissions
  - Identify Your Users
  - Track Your Users’ Actions

**Comment by beckysteele** [comment]
(I was only able to review this from a less-than-technical perspective, since I no longer have Gradle at my disposal)

In this [section](http://documentation.astronomer.io/v2/clickstream/sources/android.html#identify-your-users):
- In the second paragraph, there's an extra ` on anonymousID
