### ISSUE TITLE
Build Connector Page for Netmining

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#52]
@ryw commented on [Wed Sep 27 2017](https://github.com/astronomerio/customer/issues/176)

@benjamingregory commented on [Thu Aug 03 2017](https://github.com/astronomerio/astronomer-docs/issues/120)

---

@benjamingregory commented on [Thu Aug 10 2017](https://github.com/astronomerio/astronomer-docs/issues/120#issuecomment-321617625)

Contingent on https://github.com/astronomerio/airflow_and_pipes_issues/issues/21

**Comment by sammf** [comment]
All currently supported Clickstream sources and destinations (as they appear in the front-end) will be re-written as a part of the new docs push. Appropriate tasks have been created in the documentation repository on GitHub.
