### ISSUE TITLE
Update Keen IO Docs

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#53]
@ryw commented on [Wed Sep 27 2017](https://github.com/astronomerio/customer/issues/175)

@benjamingregory commented on [Wed Aug 09 2017](https://github.com/astronomerio/astronomer-docs/issues/133)

Waiting on UI Changes

**Comment by paolaperaza** [comment]
Closing this out, duplicate with [21](https://github.com/astronomerio/documentation/issues/21)
