### ISSUE TITLE
Oct Docs Sprint

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#55]
@ryw commented on [Wed Sep 27 2017](https://github.com/astronomerio/customer/issues/173)

@lindajguo commented on [Tue Sep 26 2017](https://github.com/astronomerio/astronomer-docs/issues/139)

- [ ] Point Astro-Metal to 2.0

- [ ] Proofread Clickstream Source Quick Start Guides

- [ ] Clickstream Destination Guides

- [ ] Clickstream Source Guides (Full Version)

- [ ] Add Pro Section to Astronomer Docs 2.0

- [ ] Iterate on Pro docs based on trialists' feedback

- [ ] Advanced Guides & Tutorials

**Comment by sammf** [comment]
This has been discussed and retooled a bit. Milestones will be created in the documentation repository on GitHub.
