### ISSUE TITLE
Create DAG Monitoring Documentation

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#56]
@andscoop commented on [Mon Oct 02 2017](https://github.com/astronomerio/customer/issues/214)

Create documentation that discusses various ways to monitor DAG success and failures.

---

@andscoop commented on [Wed Oct 04 2017](https://github.com/astronomerio/customer/issues/214#issuecomment-334249284)

https://github.com/astronomerio/docker-airflow-saas/wiki/DAG-Monitoring

**Comment by sammf** [comment]
@lindajguo - Can you incorporate any appropriate sections of @andscoop's wiki into the external Airflow docs work that you're doing? Feel free to close this issue if you already have one created.

**Comment by ryw** [comment]
Moved the wiki contents into a new `monitoring` tutorial, feel free to rearrange.
