### ISSUE TITLE
Wiki entry for data warehouse access guidelines

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#57]
@ryw commented on [Wed Sep 27 2017](https://github.com/astronomerio/customer/issues/195)

@abrongersma commented on [Tue Sep 12 2017](https://github.com/astronomerio/engineering/issues/279)

- [x] what data warehouse should be used for what

- [x] when to use personal credentials 

- [x] when to create a service account

---

@benjamingregory commented on [Wed Sep 13 2017](https://github.com/astronomerio/engineering/issues/279#issuecomment-329182120)

@abrongersma @sammf 

First draft here: https://github.com/astronomerio/engineering/wiki/Data-Warehouse-Structure---Policy

**Comment by sammf** [comment]
This is internal documentation and doesn't belong in the documentation repository, since it's a public repo.

**Comment by sammf** [comment]
Issue moved to [astronomerio/product #24](https://github.com/astronomerio/product/issues/24) via [**ZenHub**](https://www.zenhub.com/)
