### ISSUE TITLE
deploy new docs site to https://docs.astronomer.io

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#58]

**Comment by sammf** [comment]
We should be able to get a minimally viable amount of documentation by Wednesday of next week. We'll plan on redirecting [https://docs.astronomer.io](https://docs.astronomer.io) as soon as that threshold is met.

**Comment by abrongersma** [comment]
The site now points to https://docs.astronomer.io with a redirect from documentation.astronomer.io to the HTTPS site.
