### ISSUE TITLE
Fix navigation issue in longer docs

### ISSUE THREAD

**Issue by petedejoy** [astronomerio/documentation#59]
If you click a link in the table of contents and jump to a section of the doc, there's no easy way to get back to the top without scrolling. This is an issue on our longer docs like the Server-Side sources one.

**Comment by abrongersma** [comment]
Per our discussion. We clicking the left nav will take you back to the top of the page. Or you can add a goto top button inside of each section.

**Comment by petedejoy** [comment]
Issue has been resolved by dividing up long docs into separate documents (ie. Server Side-->HTTP, Node.js, MeteorJS, etc).
