### ISSUE TITLE
Sources: iOS

### ISSUE THREAD

**Issue by petedejoy** [astronomerio/documentation#61]

**Comment by beckysteele** [comment]
In this [section]():
- I recommend linking "Cocoapods" directly to our pod page, https://cocoapods.org/pods/AstronomerAnalytics
- Sidenote: it may be worth having an engineer update the pod page if we don't want it to link to Segment's docs

Other than that, this is MUCH better written than it ever was!

**Comment by petedejoy** [comment]
Cocoapods link fixed
