### ISSUE TITLE
Pebble Post

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#70]
Currently cranking this out. I wrote the context on the integration and just need to figure out how a customer would identify their `Site ID` and and `endURL Mappings` from the Pebble Post side.

**Comment by ryw** [comment]
We should crunch through these `Low Priority` issues this week @paolaperaza @petedejoy - let's get to zero open issues in this repo. No good reason not to w/ 4-person product team.

**Comment by paolaperaza** [comment]
MVP up!
