### ISSUE TITLE
AppBoy

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#73]
[Segment Documentation](https://segment.com/docs/destinations/appboy/)

[AppBoy Site](https://www.appboy.com/)

**Comment by petedejoy** [comment]
MVP deployed.

**Comment by paolaperaza** [comment]
Appboy [rebranded to Braze](https://www.braze.com/documentation/braze_faqs/?utm_campaign=2017-Braze-Launch&utm_medium=Appboy-Dashboard&utm_source=Dashboard-Email), so I went ahead and updated our docs to reflect the new name.

We have not changed the title of the doc because customers will likely still know Braze by its former name, but we have made a note to make that change in 2 weeks.
