### ISSUE TITLE
VWO

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#88]
Not a Segment integration, but [here's](https://vwo.com/?ads_cmpid=341805563&ads_adid=37553346198&ads_matchtype=e&ads_network=g&ads_creative=159895697715&utm_term=vwo&ads_targetid=kwd-165066440&utm_source=adwords&utm_medium=ppc&ttv=2&gclid=EAIaIQobChMIvd-wjMv91gIVF1mGCh04jQmkEAAYASAAEgLJPPD_BwE) the link to their direct site

**Comment by petedejoy** [comment]
Final MVP version deployed.
