### ISSUE TITLE
Clarification: Can we put together a list of standard terms for writing copy?

### ISSUE THREAD

**Issue by abrongersma** [astronomerio/documentation#95]
For consistency let's cover standard terms. 

- JavaScript not javascript 
- Developers over Devs
- Apps vs Applications
- SDKs not SDK's

**Comment by paolaperaza** [comment]
@abrongersma for sure - I can go through everything today to standardize all of the above. I'll change to JavaScript, Developers, Applications, and SDKs. 

Is there anything else?

**Comment by paolaperaza** [comment]
Went through all the destinations and made above changes. 

Closed by 613e7a077efc75e2bae8a6a21e334d6c1ac2e932
