### ISSUE TITLE
Houston docs

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#96]
Should be a page that talks about our Houston API and w/ overview of capabilities and link to GraphQL info/tutorials and to the explorer: http://houston-explorer.dev.astronomer.io/

**Comment by petedejoy** [comment]
@ryw In which section would that belong?

**Comment by ryw** [comment]
I think Platform, but probably needs to be mentioned in Clickstream overview page too - @thisisamurray any opinion?

**Comment by thisisamurray** [comment]
That sounds right, it's a platform interface (just not a user interface) that touches on Clickstream and Batch functionality. There are existing docs you can pull from at astronomerio.github.io/houston, and don't link to that explorer as it is primarily internal (will receive updates that we may not want public). I'll spin up a new one for public consumption that we can also get analytics on, and respond to this chain with the link.

**Comment by thisisamurray** [comment]
@petedejoy Publicly consumable API Explorer: https://houston-explorer.astronomer.io

**Comment by petedejoy** [comment]
@thisisamurray thanks so much- looks great. I'll get cranking on compiling this doc this afternoon and share with you once it's up for edits.

**Comment by ryw** [comment]
someone should do some CSS work to make the header less tall

**Comment by thisisamurray** [comment]
@ryw : @jlaneve did start style updates (astronomerio/engineering#390), should be a continuation of that. Think that may also involve merging astronomerio/public-api-houston-explorer and astronomerio/public-api-houston-explorer-v1, as there has been separate work continued on both. 

Julian, can you outline next steps to get this project unified to a point where we can continue styling it?

**Comment by jlaneve** [comment]
@thisisamurray yes, I can - can we create a separate issue for the style changes?

**Comment by petedejoy** [comment]
@jlaneve did you end up creating a separate issue? I'd like to close this one now that we've deployed the MVP Houston docs (https://docs.astronomer.io/v2/platform/api.html).

**Comment by petedejoy** [comment]
Going to close this for now since Houston docs are up and running.
